class ModelUnResolved(Exception):pass
class ModelUnReachableException(Exception):pass
class ModelScopeException(Exception):pass
class ModelStillInUseException(Exception):pass
class ModelRecursiveKeyException(Exception):pass
class ModelRecursiveKeyErrorException(Exception):pass
class ModelDisparateDatasourcesException(Exception):pass
class ModelNameNotFoundException(Exception):pass
class ModelGroupParentException(Exception):pass
class FunctionNotFoundException(Exception):pass
class AssociationStillInUseException(Exception):pass
class RowElementAlreadyDefinedException(Exception):pass
class ConfigSchemaAliasException(Exception):pass
class IdentifierNotFoundException(Exception):pass
class SQLAggregateException(Exception):pass
class SessionLeafNotTemplateException(Exception):pass
class InstanceWriteError(Exception):pass
class SQLErrorException(Exception):pass
class SQLInsertException(Exception):pass
class SQLUpdateException(Exception):pass
class SQLDeleteException(Exception):pass
class FileIOException(Exception):pass
class ConditionDuplicateException(Exception):pass
class ObjectGroupLinkException(Exception):pass